version: '3'
volumes:
  openhab-conf:
    external: true
  openhab-userdata:
    external: true
  openhab-addons:
    external: true
services:
  openhab:
    container_name: openhab
    image: openhab/openhab
    volumes:
      - openhab-conf:/conf:rw
      - openhab-userdata:/userdata:rw
      - openhab-addons:/addons:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080/tcp
    network_mode: "host"
    restart: always
