version: '3'
volumes:
  openhab-conf:
   driver: local 
   driver_opts:
     type: "nfs"
     o: "addr=192.168.0.209,nolock,soft,rw"
     device: ":/mnt/pool1/docker_data01"
  openhab-userdata:
   driver: local 
   driver_opts:
     type: "nfs"
     o: "addr=192.168.0.209,nolock,soft,rw"
     device: ":/mnt/pool1/docker_data01"
  openhab-addons:
   driver: local 
   driver_opts:
     type: "nfs"
     o: "addr=192.168.0.209,nolock,soft,rw"
     device: ":/mnt/pool1/docker_data01"
services:
  openhab:
    container_name: openhab
    image: openhab/openhab
    volumes:
      - openhab-conf:/conf:rw
      - openhab-userdata:/userdata:rw
      - openhab-addons:/addons:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080/tcp
    network_mode: "host"
    restart: always
